### ISSUE TITLE
Application resource

### ISSUE THREAD

**Issue by dtwilliamsWork** [OpenVPN/terraform-provider-cloudconnexa#5]
Can we add a new application yet or is it still WIP?

**Comment by chicco785** [comment]
it's missing on the client side: https://github.com/OpenVPN/cloudconnexa-go-client/tree/main/cloudconnexa, so first it needs to be added there, afaik.

what's weird though, is that the application api is not yet consistent with the others (this actually holds true also for IP Service):
![image](https://github.com/OpenVPN/terraform-provider-cloudconnexa/assets/777218/3aa8a9a7-03b0-489e-8f0a-c066c989bcf0)

vs

![image](https://github.com/OpenVPN/terraform-provider-cloudconnexa/assets/777218/b8962c39-2156-4bbb-a188-8c67e2e10301)

**Comment by sahaqaa** [comment]
Support for Applications was added via https://github.com/OpenVPN/terraform-provider-cloudconnexa/pull/17
Please see [examples](https://github.com/OpenVPN/terraform-provider-cloudconnexa/blob/main/example/applications.tf).

New version of the provider with support for Applications will be released within 1-2 weeks
