### ISSUE TITLE
Perpetual drift on description for default_connector in cloudconnexa_network resource

### ISSUE THREAD

**Issue by pickgr** [OpenVPN/terraform-provider-cloudconnexa#6]
I may have opened this in the wrong repo.  Please see

https://github.com/OpenVPN/cloudconnexa-go-client/issues/14

**Comment by sahaqaa** [comment]
I will take a look and try to fix it

**Comment by sahaqaa** [comment]
@pickgr This should be fixed in new release: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/0.1.2
Feel free to test and close this issue if all will be OK.

**Comment by pickgr** [comment]
Thank you @sahaqaa
